from __future__ import annotations

import unittest

from context import ROOT


REQUIRED_PROJECT_FILES = (
    "AGENTS.md",
    "docs/AUTONOMY_PROTOCOL.md",
    "docs/EXECUTION_LOOP.md",
    "docs/HUMAN_GATES.md",
    "docs/VALIDATION_MATRIX.md",
    "docs/STATUS.md",
    "docs/NEXT_ACTIONS.md",
    "docs/BACKLOG.md",
    "docs/NORTH_STAR.md",
    "docs/PRODUCT_SPEC.md",
    "docs/CAPABILITY_MAP.md",
    "docs/ROADMAP.md",
    "docs/ARCHITECTURE.md",
    "docs/VOLUMETRIC_LAYOUT_STRATEGY.md",
    "docs/ASSET_MODEL_STRATEGY.md",
    "docs/SOLVER_STRATEGY.md",
    "docs/LAYER_AND_STACKING_MODEL.md",
    "docs/ACCESSIBILITY_MODEL.md",
    "docs/EXPLODED_VIEW_STRATEGY.md",
    "docs/CALIBRATION_PROTOCOL.md",
    "docs/CAD_IR_CONTRACT.md",
    "docs/FUSION_360_GATE_REPORT.md",
    "docs/FUSION_360_STRATEGY.md",
    "docs/QUALITY_RULES.md",
    "docs/P66_TERRA_EXECUTION_CONTRACT.md",
    "docs/P67_POST_MVP_PRIORITIZATION_CONTRACT.md",
    "docs/P68_FIRST_USE_PRINT_FEEDBACK.md",
    "docs/P69_FULL_UI_UX_REVIEW_CONTRACT.md",
    "docs/P64_MULTI_SOLVER_PORTFOLIO_PROGRAM.md",
    "docs/P64_STAGED_CALCULATION_AND_FINISHING_PROGRAM.md",
    "docs/P64_L01_INCREMENTAL_STATE_EVIDENCE.md",
    "docs/P64_L02_CONTEXTUAL_LOCAL_ANALYSIS_EVIDENCE.md",
    "docs/P64_L03_EXPLICIT_STAGED_CYCLE_EVIDENCE.md",
    "docs/P64_L03R_B_MINIMAL_SOLVER_EVIDENCE.md",
    "docs/P64_L03R_C_DUAL_MATERIALIZATION_EVIDENCE.md",
    "docs/P64_L06_SOLVER_BENCHMARK_CAMPAIGN.md",
    "docs/P64_L06_AUTONOMOUS_GOAL_RUNBOOK.md",
    "docs/P64_L07_OPEN_SOLVER_TOURNAMENT_PROGRAM.md",
    "docs/P64_L07_AUTONOMOUS_GOAL_RUNBOOK.md",
    "docs/P64_L06C_OFFLINE_ADAPTER_AND_EXACT_ORACLE_CONTRACT.md",
    "docs/P64_L06C_OFFLINE_ADAPTER_AND_EXACT_ORACLE_EVIDENCE.md",
    "docs/FUTURE_PRODUCT_HORIZONS.md",
    "docs/P64_POST_SOLVE_CAPACITY_REUSE_CONTRACT.md",
    "docs/P64_V2H03_INTERNAL_VARIANT_COORDINATION_CONTRACT.md",
    "docs/P64_V2H03B_LOCAL_VARIANT_EVIDENCE.md",
    "docs/P45_M001_NON_CARD_ASSET_ARRANGEMENT_CONTRACT.md",
    "docs/P64_H04_OBSERVABILITY_AND_RESULT_TRUTH_CONTRACT.md",
    "docs/DECISIONS/ADR-0068-multi-solver-portfolio-and-truthful-results.md",
    "docs/DECISIONS/ADR-0081-open-external-solver-tournament.md",
    "docs/DECISIONS/ADR-0069-continuous-and-modular-volume-finishing.md",
    "docs/DECISIONS/ADR-0070-internal-container-variant-ownership.md",
    "docs/DECISIONS/ADR-0071-staged-local-analysis-explicit-solve-and-finalization.md",
    "docs/DECISIONS/ADR-0072-post-solve-capacity-maps-and-bounded-reuse.md",
    "docs/DECISIONS/ADR-0073-locked-asset-pose-and-local-arrangement-intents.md",
    "docs/DECISIONS/ADR-0074-minimal-layout-seeds-and-dual-materialization.md",
    "docs/P64_L03R_MINIMAL_LAYOUT_AND_MATERIALIZATION_CONTRACT.md",
    "docs/DECISIONS/ADR-TEMPLATE.md",
    "docs/DECISIONS/ADR-0061-post-mvp-sequencing-and-complement-quarantine.md",
    "docs/DECISIONS/ADR-0012-capability-driven-product-pilotage.md",
    "docs/DECISIONS/README.md",
    "docs/LOGS/README.md",
)

REQUIRED_SECTIONS = {
    "AGENTS.md": (
        "## Lecture obligatoire avant toute mission",
        "## Autonomous execution rules",
        "## Tests et validation",
    ),
    "docs/AUTONOMY_PROTOCOL.md": (
        "## Selection de mission",
        "## Pilotage par capabilities",
        "## Arrets obligatoires",
        "## Rapport final",
    ),
    "docs/EXECUTION_LOOP.md": (
        "## Boucle standard",
        "## Detail operationnel",
        "## Echecs et blocages",
    ),
    "docs/HUMAN_GATES.md": (
        "## Gates obligatoires",
        "## Format minimal d'un rapport de gate",
    ),
    "docs/VALIDATION_MATRIX.md": (
        "## Niveaux de validation",
        "## Statuts de capability",
        "## Regles de statut",
    ),
    "docs/STATUS.md": (
        "## Etat global",
        "## Phase active",
        "## Tests et verifications connus",
    ),
    "docs/NEXT_ACTIONS.md": (
        "## Prochaine action recommandée",
        "## Fin de chaque mission",
    ),
    "docs/BACKLOG.md": (
        "## Phase 0 - Fondation projet",
        "### P0-M002 - Ajouter une verification documentaire de base",
        "### P8-M001 - Specifier la grille volumetrique 3D et les layers",
    ),
    "docs/NORTH_STAR.md": (
        "## Formulation courte",
        "## Product Pillars",
        "## Definition du succes",
    ),
    "docs/PRODUCT_SPEC.md": (
        "## Produit cible",
        "## Product Pillars et capabilities",
    ),
    "docs/CAPABILITY_MAP.md": (
        "## Product Pillars",
        "## Architecture Tracks",
        "## Capabilities",
        "## Milestones utilisateur",
        "## Regle d'usage par Codex",
    ),
    "docs/ROADMAP.md": (
        "## Phase 0 - Gouvernance, autonomie, qualite",
        "## Phase 14 - Calibration, impression reelle, packaging et beta utilisable",
        "## Regle de progression",
    ),
    "docs/ARCHITECTURE.md": (
        "## Frontieres non negociables",
        "## Architecture Tracks",
        "## Couches logicielles",
    ),
    "docs/VOLUMETRIC_LAYOUT_STRATEGY.md": (
        "## Objectif",
        "## Concepts cibles",
        "## Gates",
    ),
    "docs/ASSET_MODEL_STRATEGY.md": (
        "## Objectif",
        "## Concepts cibles",
        "## Gates",
    ),
    "docs/SOLVER_STRATEGY.md": (
        "## Objectif",
        "## Strategie cible",
        "## Stratégie P64-L07 — comparer avant d'adopter",
        "## Gates",
    ),
    "docs/LAYER_AND_STACKING_MODEL.md": (
        "## Objectif",
        "## Concepts cibles",
        "## Gates",
    ),
    "docs/ACCESSIBILITY_MODEL.md": (
        "## Objectif",
        "## Concepts cibles",
        "## Gates",
    ),
    "docs/EXPLODED_VIEW_STRATEGY.md": (
        "## Objectif",
        "## Strategie cible",
        "## Gates",
    ),
    "docs/CALIBRATION_PROTOCOL.md": (
        "## Objectif",
        "## Coupons a preparer",
        "## Tableau de resultats",
        "## Regles d'interpretation",
    ),
    "docs/CAD_IR_CONTRACT.md": (
        "## Objectif",
        "## Scene V0",
        "## Operations abstraites",
        "## Extensions cible sans incompatibilite",
        "## Gate suivante",
    ),
    "docs/FUSION_360_GATE_REPORT.md": (
        "## Declencheur",
        "## Etat actuel du moteur",
        "## Options techniques",
        "## Validation demandee",
    ),
    "docs/FUSION_360_STRATEGY.md": (
        "## Decision centrale",
        "## Vue compacte et vue eclatee",
        "## Gates avant elargissement Fusion",
    ),
    "docs/QUALITY_RULES.md": (
        "## Regles de documentation",
        "## Garde-fous documentaires automatises",
    ),
    "docs/P64_MULTI_SOLVER_PORTFOLIO_PROGRAM.md": (
        "## 1. Résultat produit attendu",
        "## 5. Portefeuille algorithmique conservé",
        "## 6. Contrat commun de stratégie",
        "## 7. Sémantique honnête des résultats",
        "## 12. Séquence d'exécution verrouillée",
        "## 13. Cartes de mission exécutables",
    ),
    "docs/P64_STAGED_CALCULATION_AND_FINISHING_PROGRAM.md": (
        "## 1. Résultat produit attendu",
        "## 3. Modèle d'état cible",
        "## 5. Matrice d'invalidation normative",
        "## 9. Score local explicable",
        "## 13. Action `Calculer l'agencement`",
        "## 14. Action `Finaliser le volume`",
        "## 19. Découpage des missions",
        "## 22. Hors scope absolu",
    ),
    "docs/P64_L01_INCREMENTAL_STATE_EVIDENCE.md": (
        "## Portée livrée",
        "## Identités et fail-closed",
        "## Matrice d'invalidation vérifiée",
        "## Fixtures automatisées",
        "## Validation",
        "## Limites",
        "## Suite",
    ),
    "docs/P64_L02_CONTEXTUAL_LOCAL_ANALYSIS_EVIDENCE.md": (
        "## Portée livrée",
        "## Sous-scores explicables",
        "## Frontière et résumé progressif",
        "## Incrémentalité et absence de solve global",
        "## Validation",
        "## Limites",
        "## Suite",
    ),
    "docs/P64_L03_EXPLICIT_STAGED_CYCLE_EVIDENCE.md": (
        "## Portée livrée",
        "## État staged, provenance et cache",
        "## Finalisation de compatibilité",
        "## Rejet fail-closed",
        "## UX Fusion",
        "## Validation automatisée",
        "## Limites",
        "## Suite",
    ),
    "docs/P64_L03R_MINIMAL_LAYOUT_AND_MATERIALIZATION_CONTRACT.md": (
        "## 1. Résultat produit attendu",
        "## 4. Invariant géométrique du `minimal_layout`",
        "## 6. Portfolio de graines déterministes",
        "## 9. Couches locales, skyline et support",
        "## 11. Progressive widening et budgets",
        "## 15. Matérialisation minimale",
        "## 17. Identité et remplacement de scène Fusion",
        "## 19. Fixtures automatisées obligatoires",
        "## 20. Découpage de livraison",
        "## 22. Hors scope absolu",
    ),
    "docs/P64_L03R_B_MINIMAL_SOLVER_EVIDENCE.md": (
        "## Résultat",
        "## Contrat livré",
        "## Validation automatisée",
        "## Limites",
        "## Suite",
    ),
    "docs/P64_L03R_C_DUAL_MATERIALIZATION_EVIDENCE.md": (
        "## Résultat",
        "## Portée livrée",
        "## Identité exacte de l'artefact et de la CAD IR",
        "## Remplacement borné de la scène Fusion",
        "## UX progressive",
        "## Fixtures contractuelles couvertes",
        "## Validation automatisée",
        "## Limites",
        "## Suite",
    ),
    "docs/P64_L06_SOLVER_BENCHMARK_CAMPAIGN.md": (
        "## 1. Statut et objectif",
        "## 3. Familles de problèmes",
        "## 6. Candidats externes à comparer, pas à adopter",
        "## 8. Tiers d'exécution autonome",
        "## 9. Découpage de livraison",
        "## 12. Hors scope absolu",
    ),
    "docs/P64_L06_AUTONOMOUS_GOAL_RUNBOOK.md": (
        "## 1. Rôle et statut",
        "## 3. Préflight bloquant",
        "## 4. Enveloppe globale",
        "## 6. Matrice T0/T1 utile",
        "## 7. Construction et séparation des cas",
        "## 10. Checkpoint et pause",
        "## 12. Gate d'acceptation L06E",
        "## 15. Prompt `/goal` canonique",
    ),
    "docs/P64_L07_OPEN_SOLVER_TOURNAMENT_PROGRAM.md": (
        "## 1. Statut et résultat attendu",
        "## 2. Correction explicite de P64-L06",
        "## 5. Recherche obligatoire de l'état de l'art",
        "## 8. Corpus V2 et holdout neuf",
        "## 11. Tournoi progressif",
        "## 12. Règle d'intégration d'un à trois gagnants",
        "## 14. Missions atomiques",
        "## 16. Frontières absolues",
    ),
    "docs/P64_L07_AUTONOMOUS_GOAL_RUNBOOK.md": (
        "## 1. Rôle et statut",
        "## 3. Préflight bloquant",
        "## 4. Enveloppe globale",
        "## 6. Mission P64-L07A",
        "## 7. Mission P64-L07B",
        "## 8. Mission P64-L07C",
        "## 9. Mission P64-L07D",
        "## 11. Mission P64-L07E",
        "## 12. Gate d'acceptation finale",
        "## 17. Prompt `/goal` canonique",
    ),
    "docs/P64_L06C_OFFLINE_ADAPTER_AND_EXACT_ORACLE_CONTRACT.md": (
        "## 1. Statut et objectif",
        "## 4. Sortie commune",
        "## 5. Recertification obligatoire",
        "## 6. Modèle exact interne",
        "## 8. Refus honnêtes",
        "## 10. Frontières absolues",
    ),
    "docs/P64_L06C_OFFLINE_ADAPTER_AND_EXACT_ORACLE_EVIDENCE.md": (
        "## Résultat",
        "## Protocole réellement exposé",
        "## Preuve de recertification",
        "## Preuve du petit oracle exact",
        "## Validation automatisée",
        "## Limites",
        "## Suite",
    ),
    "docs/FUTURE_PRODUCT_HORIZONS.md": (
        "## 1. Statut et règle de lecture",
        "## 3. Registre des capacités futures",
        "## 4. Frontières de responsabilité",
        "## 5. Ce qui devient un critère solveur",
        "## 6. Mode manuel 3D différé",
        "## 7. Activation et preuves",
    ),
    "docs/P64_POST_SOLVE_CAPACITY_REUSE_CONTRACT.md": (
        "## 1. Objectif et promesse honnête",
        "## 2. Vocabulaire normatif",
        "## 9. Mémoire courte et invalidation",
        "## 10. Chemin C02 — Ajouter un asset localement",
        "## 12. Chemin C03 — Ajouter un conteneur autonome",
        "## 16. Certificats",
        "## 18. Découpage de livraison",
        "## 20. Hors scope absolu",
    ),
    "docs/P64_V2H03_INTERNAL_VARIANT_COORDINATION_CONTRACT.md": (
        "## 2. Frontières de responsabilité",
        "## 4. Identité canonique",
        "## 6. Certificat local",
        "## 8. Sélection globale sans produit cartésien",
        "## 10. Budget et monotonie",
        "## 12. Fixtures déterministes obligatoires",
        "## 13. Découpage de livraison",
        "## 15. Hors scope absolu",
    ),
    "docs/P64_V2H03B_LOCAL_VARIANT_EVIDENCE.md": (
        "## Portée vérifiée",
        "## Implémentation",
        "## Mesures du corpus déterministe",
        "## Fixtures verrouillées",
        "## Validation",
        "## Limites",
    ),
    "docs/P45_M001_NON_CARD_ASSET_ARRANGEMENT_CONTRACT.md": (
        "## 1. Résultat produit attendu",
        "## 3. Verrou absolu de pose et de Z",
        "## 4. Intentions de disposition",
        "## 17. Amendement accepté P45-M001V",
        "## 7. Certificat local P45",
        "## 10. Responsabilité P64 inchangée",
        "## 13. Fixtures obligatoires avant runtime",
        "## 15. Acceptation enregistrée",
        "## 16. Hors scope absolu",
    ),
    "docs/DECISIONS/ADR-0073-locked-asset-pose-and-local-arrangement-intents.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0074-minimal-layout-seeds-and-dual-materialization.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),    "docs/P64_H04_OBSERVABILITY_AND_RESULT_TRUTH_CONTRACT.md": (
        "## 1. Objectif",
        "## 3. Livrables obligatoires",
        "## 7. Non-objectifs absolus",
        "## 8. Acceptation automatisée",
    ),
    "docs/DECISIONS/ADR-0071-staged-local-analysis-explicit-solve-and-finalization.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0072-post-solve-capacity-maps-and-bounded-reuse.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0070-internal-container-variant-ownership.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0068-multi-solver-portfolio-and-truthful-results.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0081-open-external-solver-tournament.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0069-continuous-and-modular-volume-finishing.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Décision",
        "## Conséquences",
        "## Alternatives refusées",
        "## Suivi",
    ),
    "docs/P66_TERRA_EXECUTION_CONTRACT.md": (
        "## 1. Resultat attendu",
        "## 2. Clarification P44 a P50",
        "## 3. Decomposition obligatoire de P66",
        "## 8. Checklist humaine P66-V",
        "## 10. Interdits explicites",
        "## 12. Prompt court a donner a Terra",
    ),
    "docs/P67_POST_MVP_PRIORITIZATION_CONTRACT.md": (
        "## Objectif",
        "## Preconditions",
        "## Revue obligatoire",
        "## Decisions attendues",
        "## Sorties possibles",
        "## Interdits",
    ),
    "docs/P68_FIRST_USE_PRINT_FEEDBACK.md": (
        "## Role",
        "## Protocole minimal",
        "## Lien avec P67 et P44-P50",
        "## Sortie",
    ),
    "docs/P69_FULL_UI_UX_REVIEW_CONTRACT.md": (
        "## Objectif",
        "## Preconditions",
        "## Methode de revue",
        "## Livrable humain",
        "## Sortie",
        "## Interdits",
    ),
    "docs/DECISIONS/ADR-0061-post-mvp-sequencing-and-complement-quarantine.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Decision",
        "## Consequences",
        "## Alternatives refusees",
        "## Suivi",
    ),
    "docs/DECISIONS/README.md": (
        "## Template ADR",
        "## Format minimal",
        "## ADR existantes",
    ),
    "docs/DECISIONS/ADR-TEMPLATE.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Decision",
        "## Consequences",
        "## Alternatives refusees",
        "## Suivi",
    ),
    "docs/DECISIONS/ADR-0012-capability-driven-product-pilotage.md": (
        "## Statut",
        "## Contexte",
        "## Options",
        "## Decision",
        "## Consequences",
        "## Alternatives refusees",
        "## Suivi",
    ),
    "docs/LOGS/README.md": (
        "## Format recommande",
        "## Regles",
    ),
}


class ProjectDocumentsTests(unittest.TestCase):
    def test_required_project_control_files_exist(self) -> None:
        missing = [
            relative_path
            for relative_path in REQUIRED_PROJECT_FILES
            if not (ROOT / relative_path).is_file()
        ]

        if missing:
            self.fail("Fichiers de pilotage manquants: " + ", ".join(missing))

    def test_critical_project_control_sections_exist(self) -> None:
        missing_sections: list[str] = []

        for relative_path, required_headings in REQUIRED_SECTIONS.items():
            content = (ROOT / relative_path).read_text(encoding="utf-8")
            for heading in required_headings:
                if heading not in content:
                    missing_sections.append(f"{relative_path} -> {heading}")

        if missing_sections:
            self.fail("Sections de pilotage manquantes: " + "; ".join(missing_sections))


if __name__ == "__main__":
    unittest.main()
