"""Reserve the upper stack of boards and rulebooks before global box placement."""

from __future__ import annotations


from board_game_insert_generator.container_derivation import derive_container_plan
from board_game_insert_generator.project_v1 import ProjectNormalization, normalize_project_draft


FLAT_STACK_RESERVATION_SCHEMA_V1 = "bgig.flat_stack_reservation.v1"


def derive_flat_stack_reservation(raw_project: object) -> dict[str, object]:
    """Reserve flat items and re-derive containers below their upper stack.

    The result is intentionally pre-placement.  It determines the vertical
    space left to storage containers and the support that P41 must provide, but
    cannot promise a physical support surface before the global placement is
    solved.
    """

    normalization = normalize_project_draft(raw_project)
    project = normalization.project
    box = _mapping(project["box"])
    layout = _mapping(project["layout"])
    box_inner = _dimension(box["inner_dimensions_mm"])
    usable_height_mm = min(float(box["usable_height_mm"]), box_inner["z"])
    clearance_mm = float(layout["layout_clearance_mm"])
    items = _ordered_flat_items(
        _values(project["flat_items"]),
        clearance_mm=clearance_mm,
    )
    flat_stack, flat_blockers = _reserve_flat_stack(
        items=items,
        box_inner=box_inner,
        usable_height_mm=usable_height_mm,
        clearance_mm=clearance_mm,
    )
    storage_height_mm = float(flat_stack["storage_height_mm"])
    container_plan = derive_container_plan(
        project,
        max_container_height_mm=max(0.001, storage_height_mm) if items else None,
    )
    container_blockers: list[str] = []
    for value in _values(container_plan["blockers"]):
        entry = _mapping(value)
        container_blockers.append(f"{entry['container_name']}: {entry['message']}")
    support = _support_requirement(flat_stack, container_plan, blocked=bool(flat_blockers or container_blockers))
    blockers = [*flat_blockers, *container_blockers]
    return {
        "schema_version": FLAT_STACK_RESERVATION_SCHEMA_V1,
        "source": _source_payload(normalization),
        "project_name": project["project_name"],
        "container_plan": container_plan,
        "flat_stack": flat_stack,
        "support_requirement": support,
        "summary": {
            "status": "blocked" if blockers else "ready_for_p41",
            "flat_family_count": len(items),
            "flat_copy_count": sum(int(item["quantity"]) for item in items),
            "storage_height_mm": _round(storage_height_mm),
            "ready_container_count": _mapping(container_plan["summary"])["ready_container_count"],
            "blocked_container_count": _mapping(container_plan["summary"])["blocked_container_count"],
            "next_step": "P41 must place all containers, resolve support coverage and close the remaining volume.",
        },
        "blockers": blockers,
        "limitations": [
            "The upper stack is reserved but not yet positioned by a global X/Y/Z layout.",
            "Support is an area budget until P41 proves continuous support from placed containers or filler.",
            "No CAD, Fusion geometry or print validation is generated by this reservation.",
        ],
    }


def _ordered_flat_items(
    values: list[object],
    *,
    clearance_mm: float,
) -> list[dict[str, object]]:
    items = [_mapping(value) for value in values]
    ordered = sorted(
        items,
        key=lambda item: _automatic_flat_stack_key(
            item,
            fallback_clearance_mm=clearance_mm,
        ),
    )
    result: list[dict[str, object]] = []
    for automatic_order, source in enumerate(ordered):
        item = dict(source)
        source_order = item.get("stack_order")
        item["_automatic_stack_order"] = automatic_order
        item["_stack_order_migration"] = (
            "automatic_assigned"
            if source_order is None
            else (
                "legacy_matches_automatic"
                if int(source_order) == automatic_order
                else "legacy_overridden_by_automatic"
            )
        )
        result.append(item)
    return result


def _automatic_flat_stack_key(
    item: dict[str, object],
    *,
    fallback_clearance_mm: float,
) -> tuple[object, ...]:
    dimensions = _dimension(item["dimensions_mm"])
    effective = item.get("clearance_effective_v1")
    values = (
        _dimension(_mapping(effective)["values_mm"])
        if isinstance(effective, dict)
        else {
            "x": fallback_clearance_mm,
            "y": fallback_clearance_mm,
            "z": 0.0,
        }
    )
    oriented_x = dimensions["x"] + 2.0 * values["x"]
    oriented_y = dimensions["y"] + 2.0 * values["y"]
    return (
        _round(oriented_x * oriented_y),
        _round(max(oriented_x, oriented_y)),
        _round(min(oriented_x, oriented_y)),
        _round(dimensions["z"] * int(item["quantity"])),
        str(item["kind"]),
        str(item["id"]),
    )


def _reserve_flat_stack(
    *,
    items: list[dict[str, object]],
    box_inner: dict[str, float],
    usable_height_mm: float,
    clearance_mm: float,
) -> tuple[dict[str, object], list[str]]:
    if not items:
        return (
            {
                "status": "not_required",
                "reservation_clearance_mm": _round(clearance_mm),
                "physical_footprint_mm": None,
                "reservation_size_mm": None,
                "storage_height_mm": _round(usable_height_mm),
                "items": [],
            },
            [],
        )

    physical_x = max(float(_dimension(item["dimensions_mm"])["x"]) for item in items)
    physical_y = max(float(_dimension(item["dimensions_mm"])["y"]) for item in items)
    physical_height = sum(float(_dimension(item["dimensions_mm"])["z"]) * int(item["quantity"]) for item in items)
    reservation_size = {
        "x": _round(physical_x + clearance_mm * 2.0),
        "y": _round(physical_y + clearance_mm * 2.0),
        "z": _round(physical_height + clearance_mm),
    }
    storage_height = _round(usable_height_mm - reservation_size["z"])
    blockers: list[str] = []
    if reservation_size["x"] > box_inner["x"]:
        blockers.append(
            f"The upper flat stack needs {reservation_size['x']} mm in width but the box allows {box_inner['x']} mm."
        )
    if reservation_size["y"] > box_inner["y"]:
        blockers.append(
            f"The upper flat stack needs {reservation_size['y']} mm in depth but the box allows {box_inner['y']} mm."
        )
    if reservation_size["z"] > usable_height_mm:
        blockers.append(
            f"The upper flat stack needs {reservation_size['z']} mm in height but the usable box height is {usable_height_mm} mm."
        )

    cursor_z = storage_height + clearance_mm
    stack_items: list[dict[str, object]] = []
    for item in items:
        dimensions = _dimension(item["dimensions_mm"])
        automatic_key = _automatic_flat_stack_key(
            item,
            fallback_clearance_mm=clearance_mm,
        )
        total_thickness = dimensions["z"] * int(item["quantity"])
        stack_items.append(
            {
                "id": item["id"],
                "name": item["name"],
                "kind": item["kind"],
                "quantity": item["quantity"],
                "stack_order": item["_automatic_stack_order"],
                "source_stack_order": item["stack_order"],
                "stack_order_policy": (
                    "automatic_oriented_footprint_ascending_v1"
                ),
                "automatic_stack_key_v1": {
                    "oriented_footprint_area_mm2": automatic_key[0],
                    "oriented_long_side_mm": automatic_key[1],
                    "oriented_short_side_mm": automatic_key[2],
                    "total_thickness_mm": automatic_key[3],
                    "kind": automatic_key[4],
                    "flat_item_id": automatic_key[5],
                },
                "stack_order_migration": item[
                    "_stack_order_migration"
                ],
                "manual_stack_mode_implemented": False,
                "physical_size_mm": _rounded_dimension(dimensions),
                "total_thickness_mm": _round(total_thickness),
                "stack_origin_z_mm": _round(cursor_z),
            }
        )
        cursor_z += total_thickness
    return (
        {
            "status": "blocked" if blockers else "reserved",
            "reservation_clearance_mm": _round(clearance_mm),
            "physical_footprint_mm": {"x": _round(physical_x), "y": _round(physical_y), "z": _round(physical_height)},
            "reservation_size_mm": reservation_size,
            "storage_height_mm": storage_height,
            "preferred_reservation_origin_mm": {"x": 0.0, "y": 0.0, "z": _round(storage_height)},
            "items": stack_items,
        },
        blockers,
    )


def _support_requirement(
    flat_stack: dict[str, object], container_plan: dict[str, object], *, blocked: bool
) -> dict[str, object]:
    reservation_size = flat_stack["reservation_size_mm"]
    if reservation_size is None:
        return {
            "status": "not_required",
            "required_footprint_mm": None,
            "required_area_mm2": 0.0,
            "candidate_container_top_area_mm2": 0.0,
            "note": "No board or rulebook stack requires an upper support.",
        }
    footprint = _mapping(reservation_size)
    required_area = float(footprint["x"]) * float(footprint["y"])
    ready_containers = [
        _mapping(container)
        for container in _values(container_plan["containers"])
        if _mapping(container)["status"] == "ready"
    ]
    candidate_area = sum(
        float(_mapping(container["outer_dimensions_mm"])["x"])
        * float(_mapping(container["outer_dimensions_mm"])["y"])
        for container in ready_containers
        if container["outer_dimensions_mm"] is not None
    )
    if blocked:
        status = "blocked"
        note = "Support cannot be assessed until the flat stack and every storage container fit."
    elif candidate_area >= required_area:
        status = "area_budget_sufficient_pending_placement"
        note = "The sum of candidate container tops is sufficient, but P41 must still prove a continuous support surface."
    else:
        status = "support_extension_required"
        note = "Placed containers alone do not yet provide enough top area; P41 must extend a container or add support/filler."
    return {
        "status": status,
        "required_footprint_mm": _rounded_dimension(footprint),
        "required_area_mm2": _round(required_area),
        "candidate_container_top_area_mm2": _round(candidate_area),
        "note": note,
    }


def _source_payload(normalization: ProjectNormalization) -> dict[str, object]:
    return {
        "source_schema": normalization.source_schema,
        "migrated": normalization.migrated,
        "project_schema": str(normalization.project["schema_version"]),
    }


def _mapping(value: object) -> dict[str, object]:
    if not isinstance(value, dict):
        raise TypeError("Internal normalized project value must be a mapping.")
    return value


def _values(value: object) -> list[object]:
    if not isinstance(value, list):
        raise TypeError("Internal normalized project value must be a list.")
    return value


def _dimension(value: object) -> dict[str, float]:
    raw = _mapping(value)
    return {axis: float(raw[axis]) for axis in ("x", "y", "z")}


def _rounded_dimension(value: dict[str, object]) -> dict[str, float]:
    return {axis: _round(float(value[axis])) for axis in ("x", "y", "z")}


def _round(value: float) -> float:
    return round(float(value), 4)
